# Generated by Django 4.1.3 on 2022-11-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=9999999999)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Video_Thumbs', verbose_name='Video Thumbs')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
